# Generated by Django 4.2.14 on 2025-07-26 03:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '公司',
                'verbose_name_plural': '公司',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('department', models.CharField(blank=True, max_length=255, null=True)),
                ('salary_range', models.CharField(blank=True, max_length=100, null=True)),
                ('level_set', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('待处理', '待处理'), ('进行中', '进行中'), ('已关闭', '已关闭'), ('成功', '成功')], db_index=True, default='待处理', max_length=50)),
                ('locations', models.JSONField(blank=True, default=list)),
                ('skills', models.JSONField(blank=True, default=list)),
                ('job_description', models.TextField(blank=True, null=True)),
                ('job_requirement', models.TextField(blank=True, null=True)),
                ('keywords', models.JSONField(blank=True, default=list)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='jobs.company')),
            ],
            options={
                'verbose_name': '职位',
                'verbose_name_plural': '职位',
                'ordering': ['-updated_at'],
            },
        ),
    ]
