# Generated by Django 4.2.14 on 2025-07-28 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(help_text="服务商的唯一标识, 例如 'qwen', 'kimi'", max_length=100, unique=True)),
                ('api_key_encrypted', models.BinaryField(help_text='加密后的API密钥')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'API密钥',
                'verbose_name_plural': 'API密钥',
                'ordering': ['provider'],
            },
        ),
    ]
