# Generated by Django 4.2.14 on 2025-07-28 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_candidate_alter_apikey_api_key_encrypted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='job',
            name='skills',
        ),
        migrations.AddField(
            model_name='candidate',
            name='keywords',
            field=models.JSONField(blank=True, default=list, verbose_name='标准化关键词'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='raw_skills',
            field=models.JSONField(blank=True, default=list, verbose_name='原始技能(未处理)'),
        ),
        migrations.AddField(
            model_name='job',
            name='raw_skills',
            field=models.JSONField(blank=True, default=list, verbose_name='原始技能(未处理)'),
        ),
        migrations.AlterField(
            model_name='job',
            name='keywords',
            field=models.JSONField(blank=True, default=list, verbose_name='标准化关键词'),
        ),
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255, verbose_name='邮件主题')),
                ('content', models.TextField(verbose_name='邮件内容')),
                ('sent_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='发送时间')),
                ('status', models.CharField(choices=[('成功', '成功'), ('失败', '失败'), ('待发送', '待发送')], default='待发送', max_length=50, verbose_name='发送状态')),
                ('failure_reason', models.TextField(blank=True, null=True, verbose_name='失败原因')),
                ('retry_count', models.PositiveSmallIntegerField(default=0, verbose_name='重试次数')),
                ('trigger_type', models.CharField(choices=[('自动', '自动'), ('手动', '手动')], default='手动', max_length=50, verbose_name='触发方式')),
                ('candidate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobs.candidate', verbose_name='候选人')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobs.job', verbose_name='相关职位')),
            ],
            options={
                'verbose_name': '邮件发送记录',
                'verbose_name_plural': '邮件发送记录',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('已匹配', '已匹配'), ('已申请', '已申请'), ('面试中', '面试中'), ('已Offer', '已Offer'), ('已拒绝', '已拒绝')], default='已匹配', max_length=50, verbose_name='状态')),
                ('matched_keywords', models.JSONField(blank=True, default=list, verbose_name='匹配到的关键词')),
                ('application_date', models.DateTimeField(auto_now_add=True, verbose_name='申请/匹配日期')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.candidate', verbose_name='候选人')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.job', verbose_name='职位')),
            ],
            options={
                'verbose_name': '申请记录',
                'verbose_name_plural': '申请记录',
                'ordering': ['-application_date'],
                'unique_together': {('candidate', 'job')},
            },
        ),
        migrations.AddField(
            model_name='candidate',
            name='applications',
            field=models.ManyToManyField(related_name='candidates', through='jobs.Application', to='jobs.job'),
        ),
    ]
