# Generated by Django 4.2.14 on 2025-07-28 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_remove_candidate_skills_remove_job_skills_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='分组名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='分组描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '候选人分组',
                'verbose_name_plural': '候选人分组',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='emaillog',
            name='remarks',
            field=models.TextField(blank=True, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='candidate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_logs', to='jobs.candidate', verbose_name='候选人'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='candidates', to='jobs.candidategroup', verbose_name='所属分组'),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobs.candidategroup', verbose_name='目标分组'),
        ),
    ]
