# Generated by Django 4.2.14 on 2025-07-29 00:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0005_candidategroup_emaillog_remarks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='所属用户'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidate',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建者'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidategroup',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建者'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emaillog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='操作者'),
        ),
        migrations.AddField(
            model_name='job',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建者'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='apikey',
            name='provider',
            field=models.CharField(help_text="服务商的唯一标识, 例如 'qwen', 'kimi'", max_length=100, verbose_name='服务商'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='external_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True, verbose_name='外部系统ID'),
        ),
        migrations.AlterField(
            model_name='candidategroup',
            name='name',
            field=models.CharField(max_length=255, verbose_name='分组名称'),
        ),
        migrations.AlterUniqueTogether(
            name='apikey',
            unique_together={('user', 'provider')},
        ),
        migrations.AlterUniqueTogether(
            name='candidategroup',
            unique_together={('user', 'name')},
        ),
        migrations.CreateModel(
            name='EmailAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.EmailField(max_length=254, unique=True, verbose_name='邮箱地址')),
                ('smtp_host', models.CharField(max_length=255, verbose_name='SMTP服务器')),
                ('smtp_port', models.PositiveIntegerField(verbose_name='端口')),
                ('smtp_password_encrypted', models.BinaryField(verbose_name='加密后的密码/授权码')),
                ('use_ssl', models.BooleanField(default=True, verbose_name='使用SSL')),
                ('is_default', models.BooleanField(default=False, verbose_name='是否为默认邮箱')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_accounts', to=settings.AUTH_USER_MODEL, verbose_name='所属用户')),
            ],
            options={
                'verbose_name': '邮箱账户',
                'verbose_name_plural': '邮箱账户',
                'ordering': ['-is_default', 'email_address'],
            },
        ),
        migrations.CreateModel(
            name='ActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('action_description', models.CharField(max_length=255, verbose_name='操作描述')),
                ('related_object_str', models.CharField(blank=True, max_length=255, null=True, verbose_name='关联对象')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='操作者')),
            ],
            options={
                'verbose_name': '操作日志',
                'verbose_name_plural': '操作日志',
                'ordering': ['-action_time'],
            },
        ),
        migrations.AddField(
            model_name='emaillog',
            name='from_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobs.emailaccount', verbose_name='发件邮箱'),
        ),
    ]
