# Generated by Django 4.2.14 on 2025-07-29 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_usersignature_emailtemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaillog',
            name='is_clicked',
            field=models.BooleanField(default=False, verbose_name='是否点击'),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='is_opened',
            field=models.BooleanField(default=False, verbose_name='是否打开'),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='message_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='服务商消息ID'),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='opened_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='首次打开时间'),
        ),
    ]
