# Generated by Django 4.2.14 on 2025-07-30 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_add_email_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='出生年月日'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='education_level',
            field=models.CharField(choices=[('高中', '高中'), ('大专', '大专'), ('本科', '本科'), ('硕士', '硕士'), ('博士', '博士'), ('其他', '其他'), ('未知', '未知')], default='未知', max_length=20, verbose_name='最高学历'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='gender',
            field=models.CharField(choices=[('男', '男'), ('女', '女'), ('其他', '其他'), ('未知', '未知')], default='未知', max_length=10, verbose_name='性别'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='所在地'),
        ),
    ]
