# Generated by Django 4.2.14 on 2025-07-30 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0011_candidate_birthday_candidate_education_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='predicted_position',
            field=models.CharField(blank=True, help_text='AI根据简历内容判断该候选人目前从事或适合的职位名称', max_length=255, null=True, verbose_name='AI预测职位'),
        ),
    ]
