# Generated by Django 4.2.14 on 2025-07-30 06:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0012_candidate_predicted_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledEmailTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='任务名称')),
                ('schedule_type', models.CharField(choices=[('once', '单次发送'), ('daily', '每日发送'), ('weekly', '每周发送'), ('monthly', '每月发送'), ('custom', '自定义')], default='once', max_length=20, verbose_name='调度类型')),
                ('start_time', models.DateTimeField(verbose_name='开始时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('schedule_config', models.JSONField(blank=True, default=dict, help_text='存储具体的调度规则，如每周几、每月几号等', verbose_name='调度配置')),
                ('status', models.CharField(choices=[('active', '启用'), ('paused', '暂停'), ('completed', '已完成'), ('cancelled', '已取消')], default='active', max_length=20, verbose_name='任务状态')),
                ('last_run_time', models.DateTimeField(blank=True, null=True, verbose_name='上次执行时间')),
                ('next_run_time', models.DateTimeField(blank=True, null=True, verbose_name='下次执行时间')),
                ('total_executions', models.PositiveIntegerField(default=0, verbose_name='总执行次数')),
                ('successful_executions', models.PositiveIntegerField(default=0, verbose_name='成功次数')),
                ('failed_executions', models.PositiveIntegerField(default=0, verbose_name='失败次数')),
                ('description', models.TextField(blank=True, null=True, verbose_name='任务描述')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('from_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.emailaccount', verbose_name='发件邮箱')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_tasks', to='jobs.candidategroup', verbose_name='目标分组')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.emailtemplate', verbose_name='邮件模板')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            options={
                'verbose_name': '定时邮件任务',
                'verbose_name_plural': '定时邮件任务',
                'ordering': ['-created_at'],
            },
        ),
    ]
