# Generated by Django 4.2.14 on 2025-07-30 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0013_scheduledemailtask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailreply',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_replies', to='jobs.candidate', verbose_name='发件候选人'),
        ),
        migrations.AlterField(
            model_name='emailreply',
            name='in_reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_replies', to='jobs.emaillog', verbose_name='回复的邮件'),
        ),
        migrations.AlterField(
            model_name='emailreply',
            name='to_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_replies', to='jobs.emailaccount', verbose_name='收件账户'),
        ),
        migrations.CreateModel(
            name='IncomingEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_email', models.EmailField(max_length=254, verbose_name='发件人邮箱')),
                ('sender_name', models.CharField(blank=True, max_length=255, verbose_name='发件人姓名')),
                ('subject', models.CharField(max_length=500, verbose_name='邮件主题')),
                ('content', models.TextField(verbose_name='邮件内容')),
                ('html_content', models.TextField(blank=True, null=True, verbose_name='HTML内容')),
                ('message_id', models.CharField(max_length=255, unique=True, verbose_name='邮件消息ID')),
                ('in_reply_to', models.CharField(blank=True, max_length=255, null=True, verbose_name='回复的消息ID')),
                ('references', models.TextField(blank=True, null=True, verbose_name='引用消息ID')),
                ('received_at', models.DateTimeField(verbose_name='收到时间')),
                ('processed_at', models.DateTimeField(auto_now_add=True, verbose_name='处理时间')),
                ('email_type', models.CharField(choices=[('reply', '回复'), ('auto_reply', '自动回复'), ('bounce', '退信'), ('other', '其他')], default='reply', max_length=20, verbose_name='邮件类型')),
                ('is_read', models.BooleanField(default=False, verbose_name='是否已读')),
                ('is_important', models.BooleanField(default=False, verbose_name='是否重要')),
                ('attachments_count', models.PositiveIntegerField(default=0, verbose_name='附件数量')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('candidate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_emails', to='jobs.candidate', verbose_name='关联候选人')),
                ('original_email_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_replies', to='jobs.emaillog', verbose_name='原始邮件')),
                ('received_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobs.emailaccount', verbose_name='接收邮箱')),
            ],
            options={
                'verbose_name': '收件邮件',
                'verbose_name_plural': '收件邮件',
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailAccountStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='统计日期')),
                ('sent_count', models.PositiveIntegerField(default=0, verbose_name='已发送数量')),
                ('failed_count', models.PositiveIntegerField(default=0, verbose_name='发送失败数量')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                ('email_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_stats', to='jobs.emailaccount', verbose_name='邮箱账户')),
            ],
            options={
                'verbose_name': '邮箱发送统计',
                'verbose_name_plural': '邮箱发送统计',
                'ordering': ['-date'],
                'unique_together': {('email_account', 'date')},
            },
        ),
    ]
