# Generated by Django 4.2.14 on 2025-07-30 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0014_alter_emailreply_candidate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledemailtask',
            name='selected_accounts',
            field=models.ManyToManyField(blank=True, related_name='scheduled_tasks', to='jobs.emailaccount', verbose_name='选择的邮箱账户'),
        ),
        migrations.AddField(
            model_name='scheduledemailtask',
            name='use_multi_accounts',
            field=models.BooleanField(default=False, verbose_name='使用多邮箱发送'),
        ),
        migrations.AlterField(
            model_name='scheduledemailtask',
            name='from_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.emailaccount', verbose_name='单一发件邮箱'),
        ),
    ]
