# Generated by Django 4.2.14 on 2025-07-30 08:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0015_scheduledemailtask_selected_accounts_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='姓名')),
                ('gender', models.CharField(choices=[('male', '男'), ('female', '女'), ('other', '其他'), ('unknown', '未知')], default='unknown', max_length=10, verbose_name='性别')),
                ('email', models.EmailField(db_index=True, max_length=254, verbose_name='邮箱地址')),
                ('phone', models.CharField(blank=True, db_index=True, max_length=20, verbose_name='电话号码')),
                ('position', models.CharField(blank=True, max_length=100, verbose_name='职位')),
                ('department', models.CharField(blank=True, max_length=100, verbose_name='部门')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('last_contact_date', models.DateTimeField(blank=True, null=True, verbose_name='最后联系时间')),
                ('contact_frequency', models.PositiveIntegerField(default=0, verbose_name='联系次数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否有效')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='jobs.company', verbose_name='所属公司')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_contacts', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_contacts', to=settings.AUTH_USER_MODEL, verbose_name='最后修改者')),
            ],
            options={
                'verbose_name': '联系人',
                'verbose_name_plural': '联系人',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ContactGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='分组名称')),
                ('description', models.TextField(blank=True, verbose_name='分组描述')),
                ('group_type', models.CharField(choices=[('company', '按公司分组'), ('position', '按职位分组'), ('department', '按部门分组'), ('custom', '自定义分组')], default='custom', max_length=20, verbose_name='分组类型')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_public', models.BooleanField(default=True, verbose_name='是否公开（所有用户可见）')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('contacts', models.ManyToManyField(blank=True, related_name='contact_groups', to='jobs.contact', verbose_name='分组联系人')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_contact_groups', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_contact_groups', to=settings.AUTH_USER_MODEL, verbose_name='最后修改者')),
            ],
            options={
                'verbose_name': '联系人分组',
                'verbose_name_plural': '联系人分组',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='scheduledemailtask',
            name='target_type',
            field=models.CharField(choices=[('candidate_group', '候选人分组'), ('contact_group', '联系人分组')], default='candidate_group', max_length=20, verbose_name='目标类型'),
        ),
        migrations.AlterField(
            model_name='scheduledemailtask',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_tasks', to='jobs.candidategroup', verbose_name='候选人分组'),
        ),
        migrations.AddField(
            model_name='scheduledemailtask',
            name='contact_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_tasks', to='jobs.contactgroup', verbose_name='联系人分组'),
        ),
        migrations.CreateModel(
            name='ContactOperationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('create', '新增'), ('update', '修改'), ('delete', '删除'), ('email_sent', '发送邮件'), ('group_add', '加入分组'), ('group_remove', '移出分组')], max_length=20, verbose_name='操作类型')),
                ('operation_time', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='操作时间')),
                ('operation_description', models.TextField(verbose_name='操作描述')),
                ('old_values', models.JSONField(blank=True, default=dict, verbose_name='修改前的值')),
                ('new_values', models.JSONField(blank=True, default=dict, verbose_name='修改后的值')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='操作IP')),
                ('user_agent', models.CharField(blank=True, max_length=500, verbose_name='用户代理')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operation_logs', to='jobs.contact', verbose_name='关联联系人')),
                ('contact_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operation_logs', to='jobs.contactgroup', verbose_name='关联分组')),
                ('operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
            ],
            options={
                'verbose_name': '联系人操作日志',
                'verbose_name_plural': '联系人操作日志',
                'ordering': ['-operation_time'],
                'indexes': [models.Index(fields=['operation_time'], name='jobs_contac_operati_f6ec87_idx'), models.Index(fields=['operator', 'operation_time'], name='jobs_contac_operato_c4a22c_idx'), models.Index(fields=['contact', 'operation_time'], name='jobs_contac_contact_33de0a_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['name', 'company'], name='jobs_contac_name_d280e1_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['email'], name='jobs_contac_email_b1c3cd_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['phone'], name='jobs_contac_phone_9724a8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='contact',
            unique_together={('email', 'company')},
        ),
    ]
