# Generated by Django 4.2.14 on 2025-07-30 10:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0016_contact_contactgroup_scheduledemailtask_target_type_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='contact',
            new_name='jobs_contac_name_1674b7_idx',
            old_name='jobs_contac_name_d280e1_idx',
        ),
        migrations.AddField(
            model_name='contactgroup',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建者'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='company',
            field=models.CharField(db_index=True, help_text='手动输入公司名称', max_length=200, verbose_name='所属公司'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='department',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='部门'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='notes',
            field=models.TextField(blank=True, default='', verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='position',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='职位'),
        ),
        migrations.AlterField(
            model_name='contactgroup',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='分组描述'),
        ),
        migrations.AlterField(
            model_name='contactgroup',
            name='name',
            field=models.CharField(max_length=255, verbose_name='分组名称'),
        ),
        migrations.AlterUniqueTogether(
            name='contactgroup',
            unique_together={('user', 'name')},
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['company'], name='jobs_contac_company_16b138_idx'),
        ),
        migrations.RemoveField(
            model_name='contactgroup',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='contactgroup',
            name='group_type',
        ),
        migrations.RemoveField(
            model_name='contactgroup',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='contactgroup',
            name='is_public',
        ),
        migrations.RemoveField(
            model_name='contactgroup',
            name='updated_by',
        ),
    ]
