# Generated by Django 4.2.14 on 2025-07-31 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0018_add_sender_name_to_email_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaillog',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_logs', to='jobs.contact', verbose_name='联系人'),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='contact_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobs.contactgroup', verbose_name='目标联系人分组'),
        ),
    ]
