# Generated by Django 4.2.14 on 2025-07-31 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0019_emaillog_contact_emaillog_contact_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailaccount',
            name='use_ssl',
            field=models.BooleanField(default=True, help_text='勾选以启用加密连接（根据端口自动选择TLS或SSL）', verbose_name='使用SSL/TLS加密'),
        ),
    ]
